version: "3.8"
services:
  app:
    build: ./app
    volumes:
      - ./app/src:/work

  nginx:
    image: nginx:1.18-alpine
    ports:
      - 10080:80
    volumes:
      - ./app/src:/work
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    build: ./mysql
    volumes:
      - ./mysql/db:/var/lib/mysql
